### ISSUE TITLE
Add dotnet-template tag

### ISSUE THREAD

**Issue by sayedihashimi** [tintoy/dotnet-template-templates#1]
I have created a "dotnet-template" tag in github, can you add the tag to this repository so it shows up in the [dotnet-template](https://github.com/search?q=topic%3Adotnet-template&type=Repositories) search result?

**Comment by tintoy** [comment]
Sure, thanks!

**Comment by tintoy** [comment]
Done, and did the same for my PowerShell module template.

**Comment by sayedihashimi** [comment]
Thanks closing
