### ISSUE TITLE
Change type in item template

### ISSUE THREAD

**Issue by sayedihashimi** [tintoy/dotnet-template-templates#2]
In https://github.com/tintoy/dotnet-template-templates/blob/master/src/Templates/content/ItemTemplate/.template.config/template.json the type is incorrectly set to "project" but should be item.

**Comment by tintoy** [comment]
Actually, that was deliberate - I think the problem may be one of terminology; it's a project that contains a template that creates a project representing an item template. That makes my head hurt, so here's another way of putting it:

The end result of running `dotnet new item-template -n MyItem` followed by `dotnet pack` would be a package that, if installed, would make a single item template available (`dotnet new MyItem`).

However **this** one is wrong:

https://github.com/tintoy/dotnet-template-templates/blob/9fbd0bc563f790069e500ea915365ade5cd090aa/src/Templates/content/ItemTemplate/config/_template.json#L9

That's the .template.config that the generated template will have, and that should not be marked as a project template. I'll fix that right up.

**Comment by tintoy** [comment]
PS. Thanks for the review - good catch, and much appreciated :-)

**Comment by tintoy** [comment]
Fixed in bc25e67d84b3a5cadcd74bdc10f0cb8790e4324b.
